config/routes.rb
FirehouseAppHbs2::Application.routes.draw do

    root 'static_pages#index'
    resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base

	mount_uploader :avatar, AvatarUploader
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	def index
		
		@pics = Pic.all



	end

	def new

		@pic = Pic.new 

	end

	def create
		Pic.create( pic_params )
		redirect_to pics_path
	end

	private

	def pic_params
		params.require(:pic).permit(:title,:subtitle,:message, :avatar)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehouseAppHbs2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->

      <%= link_to 'Arnold Homepage' , root_path, :class => 'brand' %> 
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav">
        	<li>
        		<%= link_to 'Results', pics_path %>
        	</li>
        	
        	<li>
        		<%= link_to 'Answers', new_pic_path %>
        	</li>
        </ul>

      </div>
 
    </div>
  </div>
</div>





<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<% @pics.each_slice(3) do |slice| %>
        <div class="row">
                <% slice.each do |pic| %>
                        <div class="span4 smurfy text-center">
                                <h1 class="custom-h1">
                                
                                <%= pic.title %>
                                </h1>
                                </br>
                                <h2 class="custom-h2">
                       
                                <%= pic.subtitle %>
                                </br>
                
                                <%= pic.message %>
                                </h2>
                                <%= image_tag pic.avatar %>
                        </div>
                <% end %>
        </div>

        <br />
        <br />
<% end %>

app/views/pics/new.html.erb
<div class="smurfy span6 offset4 text-center">
<h1 class="custom-h1"> Fill up the form please :) <h1/>
	<%= simple_form_for @pic do |f| %>
		<%= f.input :title,  label: 'Your name',placeholder: 'Mr. Chan?' %>
		<%= f.input :subtitle,  label: 'your ageeee!?' %>
		<%= f.input :message,  label: 'tellll me about urself' %>


		<%= f.input :avatar, label: "upload your image" %>

		<%= f.submit "Save",:class => "btn btn-info" %>
	<% end %>
<div/>

app/views/static_pages/index.html.erb
<br/>
<br/>
<br/>
<br/>

<div class="span6 offset4 smurfy text-center">
 

<h1 class='custom-h1'> 
Dear, 

How are you?
</h1>

<h2 >I miss you!!</h2>

	
<%= link_to 'Get started', pics_path, :class=>'btn btn-info' %>
        	


</div>